<?php
/**
 * Generates the easter egg comment in the HTML
 * This view should be added in every page of the website
 *
 * @author Antoine du HAMEL
 */

namespace BonjourParis\APIs;

use DOMComment;

const MESSAGE = <<<'TXT'

You're looking under the hood?

I hope what you are looking pleases you; it has been generated by the
PHP library I've made `aduh95/HTMLGenerator` and written by me.


TXT;
// '



return function ($doc) {
    $doc->getHead()->append(new DOMComment(MESSAGE));
};
