const MESSAGE = `

You're looking under the hood?

I hope what you are looking at pleases you; it has been generated by some open
source JavaScript tools I have written. If you are interested in how I achieve
this, you can find a more human readable version on the
[git repository](https://github.com/aduh95/aduh95.github.io).

This web page have been written with the goal of avoiding external libraries at
runtime to generate the smallest output, and allow users that do not want to run
JavaScript code to have a decent experience. It's also a playground for me to
use modern tools and APIs to write my own plugins – those may not be suitable
for another project, but they can certainly be used for inspiration.

LICENSE INFORMATION: The following document is licensed under
[CC BY-NC-ND 4.0](https://github.com/aduh95/aduh95.github.io/blob/master/LICENSE).

Generation timestamp: ${new Date().toISOString()}

`;

export default document.createComment(MESSAGE);
