<?php
/**
 * Generates the easter egg comment in the HTML
 * This view should be added in every page of the website
 *
 * @author Antoine du HAMEL
 */

namespace aduh95\Resume;

use DOMComment;
use DateTime;

const MESSAGE = <<<'TXT'

You're looking under the hood?

I hope what you are looking pleases you; it has been generated by the
PHP library I've made `aduh95/HTMLGenerator` and written by me. If you are
interested in how I achieve this, you can find a more human readable version
on the [git repository](https://github.com/aduh95/aduh95.github.io).

TXT;

const MESSAGE_ONE_FILE = <<<'TXT'

N.B.: You are currently looking at the **standalone version**, embeding images,
web fonts, CSS stylesheets and JavaScript scripts.

Generation date:

TXT;

const LICENSE_NOTICE = <<<'TXT'

LICENSE INFORMATION:
The following document is licensed under [CC BY-NC-ND 4.0](//github.com/aduh95/aduh95.github.io/blob/master/LICENSE)

It uses the following licensed content: *Please see the attached CSS file*

TXT;



return function ($doc, $outputOneFile) {

    $doc->getHead()->append(
        new DOMComment(
            MESSAGE.
            LICENSE_NOTICE.
            ($outputOneFile ?
                MESSAGE_ONE_FILE.date_create()->format(DateTime::ATOM).PHP_EOL :
                null
            )
        )
    );
};
