const MESSAGE = `

You're looking under the hood?

I hope what you are looking pleases you; it has been generated by the
PHP library I've made \`aduh95/HTMLGenerator\` and written by me. If you are
interested in how I achieve this, you can find a more human readable version
on the [git repository](https://github.com/aduh95/aduh95.github.io).

`;

const MESSAGE_ONE_FILE = `

N.B.: You are currently looking at the **standalone version**, embedding images,
web fonts, CSS stylesheets and JavaScript scripts.

Generation date:

`;

const LICENSE_NOTICE = `

LICENSE INFORMATION:
The following document is licensed under [CC BY-NC-ND 4.0](//github.com/aduh95/aduh95.github.io/blob/master/LICENSE)

It uses the following licensed content: *Please see the attached CSS file*

`;

export default document.createComment(
  [MESSAGE, LICENSE_NOTICE, new Date().toISOString()].join("")
);
